// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(ZeroTermFFI)
import ZeroTermFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_zeroterm_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_zeroterm_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate class UniffiHandleMap<T> {
    private var map: [UInt64: T] = [:]
    private let lock = NSLock()
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




/**
 * Foreign-implemented host-key prompt. The contract:
 *
 * 1. Rust calls [`HostKeyPromptCallback::on_prompt`] synchronously.
 * 2. Foreign code shows a dialog and **returns immediately** — do NOT
 * block this call on user input.
 * 3. When the user decides, foreign code calls
 * [`crate::ZeroTerm::respond_host_key`] with the same `request_id`
 * and the user's choice. That unblocks the SSH handshake on the
 * Rust side.
 * 4. If `respond_host_key` is never called (window closed, etc.), the
 * handshake is rejected by default — never silently accepted.
 *
 * `stored` is `Some(...)` only for mismatch-with-existing-known-key;
 * in that case the foreign UI should show both fingerprints and warn
 * loudly.
 */
public protocol HostKeyPromptCallback : AnyObject {
    
    func onPrompt(requestId: String, info: HostKeyInfo, stored: String?) 
    
}

/**
 * Foreign-implemented host-key prompt. The contract:
 *
 * 1. Rust calls [`HostKeyPromptCallback::on_prompt`] synchronously.
 * 2. Foreign code shows a dialog and **returns immediately** — do NOT
 * block this call on user input.
 * 3. When the user decides, foreign code calls
 * [`crate::ZeroTerm::respond_host_key`] with the same `request_id`
 * and the user's choice. That unblocks the SSH handshake on the
 * Rust side.
 * 4. If `respond_host_key` is never called (window closed, etc.), the
 * handshake is rejected by default — never silently accepted.
 *
 * `stored` is `Some(...)` only for mismatch-with-existing-known-key;
 * in that case the foreign UI should show both fingerprints and warn
 * loudly.
 */
open class HostKeyPromptCallbackImpl:
    HostKeyPromptCallback {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_zeroterm_ffi_fn_clone_hostkeypromptcallback(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_zeroterm_ffi_fn_free_hostkeypromptcallback(pointer, $0) }
    }

    

    
open func onPrompt(requestId: String, info: HostKeyInfo, stored: String?) {try! rustCall() {
    uniffi_zeroterm_ffi_fn_method_hostkeypromptcallback_on_prompt(self.uniffiClonePointer(),
        FfiConverterString.lower(requestId),
        FfiConverterTypeHostKeyInfo.lower(info),
        FfiConverterOptionString.lower(stored),$0
    )
}
}
    

}
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceHostKeyPromptCallback {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceHostKeyPromptCallback = UniffiVTableCallbackInterfaceHostKeyPromptCallback(
        onPrompt: { (
            uniffiHandle: UInt64,
            requestId: RustBuffer,
            info: RustBuffer,
            stored: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeHostKeyPromptCallback.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onPrompt(
                     requestId: try FfiConverterString.lift(requestId),
                     info: try FfiConverterTypeHostKeyInfo.lift(info),
                     stored: try FfiConverterOptionString.lift(stored)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeHostKeyPromptCallback.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface HostKeyPromptCallback: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitHostKeyPromptCallback() {
    uniffi_zeroterm_ffi_fn_init_callback_vtable_hostkeypromptcallback(&UniffiCallbackInterfaceHostKeyPromptCallback.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostKeyPromptCallback: FfiConverter {
    fileprivate static var handleMap = UniffiHandleMap<HostKeyPromptCallback>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = HostKeyPromptCallback

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> HostKeyPromptCallback {
        return HostKeyPromptCallbackImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: HostKeyPromptCallback) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostKeyPromptCallback {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: HostKeyPromptCallback, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostKeyPromptCallback_lift(_ pointer: UnsafeMutableRawPointer) throws -> HostKeyPromptCallback {
    return try FfiConverterTypeHostKeyPromptCallback.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostKeyPromptCallback_lower(_ value: HostKeyPromptCallback) -> UnsafeMutableRawPointer {
    return FfiConverterTypeHostKeyPromptCallback.lower(value)
}




/**
 * Streaming hook for an active session. The Rust side calls these as
 * PTY data flows; the foreign side feeds them into its terminal
 * renderer.
 */
public protocol SessionListener : AnyObject {
    
    /**
     * Raw bytes from the remote PTY. Stdout and stderr are merged here.
     */
    func onData(data: Data) 
    
    /**
     * Channel closed. `exit_code` is the remote process exit status if
     * the server reported one before close; `message` carries a Rust-side
     * error description (e.g. "send failed: ...") if the loop bailed
     * early.
     */
    func onClosed(exitCode: UInt32?, message: String?) 
    
}

/**
 * Streaming hook for an active session. The Rust side calls these as
 * PTY data flows; the foreign side feeds them into its terminal
 * renderer.
 */
open class SessionListenerImpl:
    SessionListener {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_zeroterm_ffi_fn_clone_sessionlistener(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_zeroterm_ffi_fn_free_sessionlistener(pointer, $0) }
    }

    

    
    /**
     * Raw bytes from the remote PTY. Stdout and stderr are merged here.
     */
open func onData(data: Data) {try! rustCall() {
    uniffi_zeroterm_ffi_fn_method_sessionlistener_on_data(self.uniffiClonePointer(),
        FfiConverterData.lower(data),$0
    )
}
}
    
    /**
     * Channel closed. `exit_code` is the remote process exit status if
     * the server reported one before close; `message` carries a Rust-side
     * error description (e.g. "send failed: ...") if the loop bailed
     * early.
     */
open func onClosed(exitCode: UInt32?, message: String?) {try! rustCall() {
    uniffi_zeroterm_ffi_fn_method_sessionlistener_on_closed(self.uniffiClonePointer(),
        FfiConverterOptionUInt32.lower(exitCode),
        FfiConverterOptionString.lower(message),$0
    )
}
}
    

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceSessionListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    static var vtable: UniffiVTableCallbackInterfaceSessionListener = UniffiVTableCallbackInterfaceSessionListener(
        onData: { (
            uniffiHandle: UInt64,
            data: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeSessionListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onData(
                     data: try FfiConverterData.lift(data)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onClosed: { (
            uniffiHandle: UInt64,
            exitCode: RustBuffer,
            message: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeSessionListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onClosed(
                     exitCode: try FfiConverterOptionUInt32.lift(exitCode),
                     message: try FfiConverterOptionString.lift(message)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeSessionListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface SessionListener: handle missing in uniffiFree")
            }
        }
    )
}

private func uniffiCallbackInitSessionListener() {
    uniffi_zeroterm_ffi_fn_init_callback_vtable_sessionlistener(&UniffiCallbackInterfaceSessionListener.vtable)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionListener: FfiConverter {
    fileprivate static var handleMap = UniffiHandleMap<SessionListener>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = SessionListener

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> SessionListener {
        return SessionListenerImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: SessionListener) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionListener {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: SessionListener, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionListener_lift(_ pointer: UnsafeMutableRawPointer) throws -> SessionListener {
    return try FfiConverterTypeSessionListener.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionListener_lower(_ value: SessionListener) -> UnsafeMutableRawPointer {
    return FfiConverterTypeSessionListener.lower(value)
}




/**
 * Entry point for the FFI surface. Construct one per app process,
 * store it in a long-lived holder on the host (a singleton, an
 * `ObservableObject`, etc.).
 */
public protocol ZeroTermProtocol : AnyObject {
    
    /**
     * Connect to a saved host and open a PTY-backed shell. Streams data
     * into `listener.on_data`; surfaces unknown / mismatched host keys
     * via `host_key_prompt.on_prompt` (which must be answered via
     * [`Self::respond_host_key`]).
     *
     * Returns the new `session_id`. Use it with [`Self::send_input`],
     * [`Self::resize_session`], [`Self::disconnect_session`].
     */
    func connectHost(hostId: String, cols: UInt16, rows: UInt16, listener: SessionListener, hostKeyPrompt: HostKeyPromptCallback) async throws  -> UInt64
    
    func create(password: String, remember: Bool) throws 
    
    func deleteHost(id: String) throws 
    
    func disconnectSession(sessionId: UInt64) async throws 
    
    /**
     * Drop any cached master password for the current vault path.
     */
    func forgetKeychain() throws 
    
    func listHosts() throws  -> [HostSummary]
    
    func lock() 
    
    func resizeSession(sessionId: UInt64, cols: UInt16, rows: UInt16) async throws 
    
    /**
     * Answer a pending host-key prompt. `accept = true` continues the
     * SSH handshake; `false` cancels it.
     */
    func respondHostKey(requestId: String, accept: Bool) throws 
    
    func saveHost(host: HostInput) throws  -> String
    
    func sendInput(sessionId: UInt64, data: Data) async throws 
    
    /**
     * Use a custom vault path instead of the OS default. Pass empty
     * string to revert to the OS default.
     */
    func setVaultPath(path: String) 
    
    /**
     * Try to unlock the vault using the OS keychain-cached master
     * password, if any. Returns `true` on success, `false` if there's no
     * cache, the cache is stale, or the keychain backend is unavailable.
     * Never errors — keychain absence is a normal state.
     */
    func tryKeychainUnlock() throws  -> Bool
    
    func unlock(password: String, remember: Bool) throws 
    
    func vaultStatus() throws  -> VaultStatus
    
}

/**
 * Entry point for the FFI surface. Construct one per app process,
 * store it in a long-lived holder on the host (a singleton, an
 * `ObservableObject`, etc.).
 */
open class ZeroTerm:
    ZeroTermProtocol {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_zeroterm_ffi_fn_clone_zeroterm(self.pointer, $0) }
    }
public convenience init() {
    let pointer =
        try! rustCall() {
    uniffi_zeroterm_ffi_fn_constructor_zeroterm_new($0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_zeroterm_ffi_fn_free_zeroterm(pointer, $0) }
    }

    

    
    /**
     * Connect to a saved host and open a PTY-backed shell. Streams data
     * into `listener.on_data`; surfaces unknown / mismatched host keys
     * via `host_key_prompt.on_prompt` (which must be answered via
     * [`Self::respond_host_key`]).
     *
     * Returns the new `session_id`. Use it with [`Self::send_input`],
     * [`Self::resize_session`], [`Self::disconnect_session`].
     */
open func connectHost(hostId: String, cols: UInt16, rows: UInt16, listener: SessionListener, hostKeyPrompt: HostKeyPromptCallback)async throws  -> UInt64 {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_zeroterm_ffi_fn_method_zeroterm_connect_host(
                    self.uniffiClonePointer(),
                    FfiConverterString.lower(hostId),FfiConverterUInt16.lower(cols),FfiConverterUInt16.lower(rows),FfiConverterTypeSessionListener.lower(listener),FfiConverterTypeHostKeyPromptCallback.lower(hostKeyPrompt)
                )
            },
            pollFunc: ffi_zeroterm_ffi_rust_future_poll_u64,
            completeFunc: ffi_zeroterm_ffi_rust_future_complete_u64,
            freeFunc: ffi_zeroterm_ffi_rust_future_free_u64,
            liftFunc: FfiConverterUInt64.lift,
            errorHandler: FfiConverterTypeFfiError.lift
        )
}
    
open func create(password: String, remember: Bool)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeroterm_ffi_fn_method_zeroterm_create(self.uniffiClonePointer(),
        FfiConverterString.lower(password),
        FfiConverterBool.lower(remember),$0
    )
}
}
    
open func deleteHost(id: String)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeroterm_ffi_fn_method_zeroterm_delete_host(self.uniffiClonePointer(),
        FfiConverterString.lower(id),$0
    )
}
}
    
open func disconnectSession(sessionId: UInt64)async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_zeroterm_ffi_fn_method_zeroterm_disconnect_session(
                    self.uniffiClonePointer(),
                    FfiConverterUInt64.lower(sessionId)
                )
            },
            pollFunc: ffi_zeroterm_ffi_rust_future_poll_void,
            completeFunc: ffi_zeroterm_ffi_rust_future_complete_void,
            freeFunc: ffi_zeroterm_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError.lift
        )
}
    
    /**
     * Drop any cached master password for the current vault path.
     */
open func forgetKeychain()throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeroterm_ffi_fn_method_zeroterm_forget_keychain(self.uniffiClonePointer(),$0
    )
}
}
    
open func listHosts()throws  -> [HostSummary] {
    return try  FfiConverterSequenceTypeHostSummary.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeroterm_ffi_fn_method_zeroterm_list_hosts(self.uniffiClonePointer(),$0
    )
})
}
    
open func lock() {try! rustCall() {
    uniffi_zeroterm_ffi_fn_method_zeroterm_lock(self.uniffiClonePointer(),$0
    )
}
}
    
open func resizeSession(sessionId: UInt64, cols: UInt16, rows: UInt16)async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_zeroterm_ffi_fn_method_zeroterm_resize_session(
                    self.uniffiClonePointer(),
                    FfiConverterUInt64.lower(sessionId),FfiConverterUInt16.lower(cols),FfiConverterUInt16.lower(rows)
                )
            },
            pollFunc: ffi_zeroterm_ffi_rust_future_poll_void,
            completeFunc: ffi_zeroterm_ffi_rust_future_complete_void,
            freeFunc: ffi_zeroterm_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError.lift
        )
}
    
    /**
     * Answer a pending host-key prompt. `accept = true` continues the
     * SSH handshake; `false` cancels it.
     */
open func respondHostKey(requestId: String, accept: Bool)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeroterm_ffi_fn_method_zeroterm_respond_host_key(self.uniffiClonePointer(),
        FfiConverterString.lower(requestId),
        FfiConverterBool.lower(accept),$0
    )
}
}
    
open func saveHost(host: HostInput)throws  -> String {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeroterm_ffi_fn_method_zeroterm_save_host(self.uniffiClonePointer(),
        FfiConverterTypeHostInput.lower(host),$0
    )
})
}
    
open func sendInput(sessionId: UInt64, data: Data)async throws  {
    return
        try  await uniffiRustCallAsync(
            rustFutureFunc: {
                uniffi_zeroterm_ffi_fn_method_zeroterm_send_input(
                    self.uniffiClonePointer(),
                    FfiConverterUInt64.lower(sessionId),FfiConverterData.lower(data)
                )
            },
            pollFunc: ffi_zeroterm_ffi_rust_future_poll_void,
            completeFunc: ffi_zeroterm_ffi_rust_future_complete_void,
            freeFunc: ffi_zeroterm_ffi_rust_future_free_void,
            liftFunc: { $0 },
            errorHandler: FfiConverterTypeFfiError.lift
        )
}
    
    /**
     * Use a custom vault path instead of the OS default. Pass empty
     * string to revert to the OS default.
     */
open func setVaultPath(path: String) {try! rustCall() {
    uniffi_zeroterm_ffi_fn_method_zeroterm_set_vault_path(self.uniffiClonePointer(),
        FfiConverterString.lower(path),$0
    )
}
}
    
    /**
     * Try to unlock the vault using the OS keychain-cached master
     * password, if any. Returns `true` on success, `false` if there's no
     * cache, the cache is stale, or the keychain backend is unavailable.
     * Never errors — keychain absence is a normal state.
     */
open func tryKeychainUnlock()throws  -> Bool {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeroterm_ffi_fn_method_zeroterm_try_keychain_unlock(self.uniffiClonePointer(),$0
    )
})
}
    
open func unlock(password: String, remember: Bool)throws  {try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeroterm_ffi_fn_method_zeroterm_unlock(self.uniffiClonePointer(),
        FfiConverterString.lower(password),
        FfiConverterBool.lower(remember),$0
    )
}
}
    
open func vaultStatus()throws  -> VaultStatus {
    return try  FfiConverterTypeVaultStatus.lift(try rustCallWithError(FfiConverterTypeFfiError.lift) {
    uniffi_zeroterm_ffi_fn_method_zeroterm_vault_status(self.uniffiClonePointer(),$0
    )
})
}
    

}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeZeroTerm: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = ZeroTerm

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> ZeroTerm {
        return ZeroTerm(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: ZeroTerm) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ZeroTerm {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: ZeroTerm, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZeroTerm_lift(_ pointer: UnsafeMutableRawPointer) throws -> ZeroTerm {
    return try FfiConverterTypeZeroTerm.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeZeroTerm_lower(_ value: ZeroTerm) -> UnsafeMutableRawPointer {
    return FfiConverterTypeZeroTerm.lower(value)
}


/**
 * Input for [`crate::ZeroTerm::save_host`]. `id` is assigned by the
 * vault on insert, so callers don't supply one.
 */
public struct HostInput {
    public var name: String
    public var host: String
    public var port: UInt16
    public var user: String
    public var auth: HostAuthInput

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, host: String, port: UInt16, user: String, auth: HostAuthInput) {
        self.name = name
        self.host = host
        self.port = port
        self.user = user
        self.auth = auth
    }
}



extension HostInput: Equatable, Hashable {
    public static func ==(lhs: HostInput, rhs: HostInput) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.host != rhs.host {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        if lhs.user != rhs.user {
            return false
        }
        if lhs.auth != rhs.auth {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(host)
        hasher.combine(port)
        hasher.combine(user)
        hasher.combine(auth)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostInput: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostInput {
        return
            try HostInput(
                name: FfiConverterString.read(from: &buf), 
                host: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                user: FfiConverterString.read(from: &buf), 
                auth: FfiConverterTypeHostAuthInput.read(from: &buf)
        )
    }

    public static func write(_ value: HostInput, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterString.write(value.user, into: &buf)
        FfiConverterTypeHostAuthInput.write(value.auth, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostInput_lift(_ buf: RustBuffer) throws -> HostInput {
    return try FfiConverterTypeHostInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostInput_lower(_ value: HostInput) -> RustBuffer {
    return FfiConverterTypeHostInput.lower(value)
}


/**
 * Information about a server's offered host key, surfaced to the
 * foreign UI when the user must decide whether to trust it.
 */
public struct HostKeyInfo {
    public var host: String
    public var port: UInt16
    public var keyType: String
    /**
     * SHA256 fingerprint in OpenSSH style: `SHA256:<base64-no-pad>`.
     */
    public var fingerprint: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(host: String, port: UInt16, keyType: String, 
        /**
         * SHA256 fingerprint in OpenSSH style: `SHA256:<base64-no-pad>`.
         */fingerprint: String) {
        self.host = host
        self.port = port
        self.keyType = keyType
        self.fingerprint = fingerprint
    }
}



extension HostKeyInfo: Equatable, Hashable {
    public static func ==(lhs: HostKeyInfo, rhs: HostKeyInfo) -> Bool {
        if lhs.host != rhs.host {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        if lhs.keyType != rhs.keyType {
            return false
        }
        if lhs.fingerprint != rhs.fingerprint {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(host)
        hasher.combine(port)
        hasher.combine(keyType)
        hasher.combine(fingerprint)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostKeyInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostKeyInfo {
        return
            try HostKeyInfo(
                host: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                keyType: FfiConverterString.read(from: &buf), 
                fingerprint: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: HostKeyInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterString.write(value.keyType, into: &buf)
        FfiConverterString.write(value.fingerprint, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostKeyInfo_lift(_ buf: RustBuffer) throws -> HostKeyInfo {
    return try FfiConverterTypeHostKeyInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostKeyInfo_lower(_ value: HostKeyInfo) -> RustBuffer {
    return FfiConverterTypeHostKeyInfo.lower(value)
}


public struct HostSummary {
    public var id: String
    public var name: String
    public var host: String
    public var port: UInt16
    public var user: String
    public var authKind: AuthKind

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, host: String, port: UInt16, user: String, authKind: AuthKind) {
        self.id = id
        self.name = name
        self.host = host
        self.port = port
        self.user = user
        self.authKind = authKind
    }
}



extension HostSummary: Equatable, Hashable {
    public static func ==(lhs: HostSummary, rhs: HostSummary) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.name != rhs.name {
            return false
        }
        if lhs.host != rhs.host {
            return false
        }
        if lhs.port != rhs.port {
            return false
        }
        if lhs.user != rhs.user {
            return false
        }
        if lhs.authKind != rhs.authKind {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(name)
        hasher.combine(host)
        hasher.combine(port)
        hasher.combine(user)
        hasher.combine(authKind)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostSummary {
        return
            try HostSummary(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                host: FfiConverterString.read(from: &buf), 
                port: FfiConverterUInt16.read(from: &buf), 
                user: FfiConverterString.read(from: &buf), 
                authKind: FfiConverterTypeAuthKind.read(from: &buf)
        )
    }

    public static func write(_ value: HostSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.host, into: &buf)
        FfiConverterUInt16.write(value.port, into: &buf)
        FfiConverterString.write(value.user, into: &buf)
        FfiConverterTypeAuthKind.write(value.authKind, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSummary_lift(_ buf: RustBuffer) throws -> HostSummary {
    return try FfiConverterTypeHostSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSummary_lower(_ value: HostSummary) -> RustBuffer {
    return FfiConverterTypeHostSummary.lower(value)
}


public struct VaultStatus {
    public var path: String
    public var exists: Bool
    public var unlocked: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, exists: Bool, unlocked: Bool) {
        self.path = path
        self.exists = exists
        self.unlocked = unlocked
    }
}



extension VaultStatus: Equatable, Hashable {
    public static func ==(lhs: VaultStatus, rhs: VaultStatus) -> Bool {
        if lhs.path != rhs.path {
            return false
        }
        if lhs.exists != rhs.exists {
            return false
        }
        if lhs.unlocked != rhs.unlocked {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(path)
        hasher.combine(exists)
        hasher.combine(unlocked)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVaultStatus: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VaultStatus {
        return
            try VaultStatus(
                path: FfiConverterString.read(from: &buf), 
                exists: FfiConverterBool.read(from: &buf), 
                unlocked: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: VaultStatus, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterBool.write(value.exists, into: &buf)
        FfiConverterBool.write(value.unlocked, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaultStatus_lift(_ buf: RustBuffer) throws -> VaultStatus {
    return try FfiConverterTypeVaultStatus.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVaultStatus_lower(_ value: VaultStatus) -> RustBuffer {
    return FfiConverterTypeVaultStatus.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum AuthKind {
    
    case password
    case privateKey
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAuthKind: FfiConverterRustBuffer {
    typealias SwiftType = AuthKind

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AuthKind {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .password
        
        case 2: return .privateKey
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AuthKind, into buf: inout [UInt8]) {
        switch value {
        
        
        case .password:
            writeInt(&buf, Int32(1))
        
        
        case .privateKey:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthKind_lift(_ buf: RustBuffer) throws -> AuthKind {
    return try FfiConverterTypeAuthKind.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAuthKind_lower(_ value: AuthKind) -> RustBuffer {
    return FfiConverterTypeAuthKind.lower(value)
}



extension AuthKind: Equatable, Hashable {}




public enum FfiError {

    
    
    /**
     * Vault operations were attempted before [`crate::ZeroTerm::unlock`]
     * or [`crate::ZeroTerm::create`] succeeded.
     */
    case VaultLocked
    /**
     * Master password rejected. The vault file is intact; retry with the
     * correct password.
     */
    case AuthenticationFailed
    /**
     * `unlock` was called against a path that has no vault yet.
     */
    case NotInitialized
    /**
     * `create` was called against a path that already has a vault.
     */
    case AlreadyExists
    case NotFound(message: String
    )
    /**
     * Catch-all for anything that doesn't fit a more specific case —
     * IO errors, malformed records, name collisions, etc. The `message`
     * is `Display` of the underlying error.
     */
    case Other(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeFfiError: FfiConverterRustBuffer {
    typealias SwiftType = FfiError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> FfiError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .VaultLocked
        case 2: return .AuthenticationFailed
        case 3: return .NotInitialized
        case 4: return .AlreadyExists
        case 5: return .NotFound(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .Other(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: FfiError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case .VaultLocked:
            writeInt(&buf, Int32(1))
        
        
        case .AuthenticationFailed:
            writeInt(&buf, Int32(2))
        
        
        case .NotInitialized:
            writeInt(&buf, Int32(3))
        
        
        case .AlreadyExists:
            writeInt(&buf, Int32(4))
        
        
        case let .NotFound(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Other(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


extension FfiError: Equatable, Hashable {}

extension FfiError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum HostAuthInput {
    
    case password(value: String
    )
    case privateKey(keyPem: String, passphrase: String?
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostAuthInput: FfiConverterRustBuffer {
    typealias SwiftType = HostAuthInput

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostAuthInput {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .password(value: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .privateKey(keyPem: try FfiConverterString.read(from: &buf), passphrase: try FfiConverterOptionString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HostAuthInput, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .password(value):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(value, into: &buf)
            
        
        case let .privateKey(keyPem,passphrase):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(keyPem, into: &buf)
            FfiConverterOptionString.write(passphrase, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostAuthInput_lift(_ buf: RustBuffer) throws -> HostAuthInput {
    return try FfiConverterTypeHostAuthInput.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostAuthInput_lower(_ value: HostAuthInput) -> RustBuffer {
    return FfiConverterTypeHostAuthInput.lower(value)
}



extension HostAuthInput: Equatable, Hashable {}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeHostSummary: FfiConverterRustBuffer {
    typealias SwiftType = [HostSummary]

    public static func write(_ value: [HostSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeHostSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [HostSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [HostSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeHostSummary.read(from: &buf))
        }
        return seq
    }
}
private let UNIFFI_RUST_FUTURE_POLL_READY: Int8 = 0
private let UNIFFI_RUST_FUTURE_POLL_MAYBE_READY: Int8 = 1

fileprivate let uniffiContinuationHandleMap = UniffiHandleMap<UnsafeContinuation<Int8, Never>>()

fileprivate func uniffiRustCallAsync<F, T>(
    rustFutureFunc: () -> UInt64,
    pollFunc: (UInt64, @escaping UniffiRustFutureContinuationCallback, UInt64) -> (),
    completeFunc: (UInt64, UnsafeMutablePointer<RustCallStatus>) -> F,
    freeFunc: (UInt64) -> (),
    liftFunc: (F) throws -> T,
    errorHandler: ((RustBuffer) throws -> Swift.Error)?
) async throws -> T {
    // Make sure to call uniffiEnsureInitialized() since future creation doesn't have a
    // RustCallStatus param, so doesn't use makeRustCall()
    uniffiEnsureInitialized()
    let rustFuture = rustFutureFunc()
    defer {
        freeFunc(rustFuture)
    }
    var pollResult: Int8;
    repeat {
        pollResult = await withUnsafeContinuation {
            pollFunc(
                rustFuture,
                uniffiFutureContinuationCallback,
                uniffiContinuationHandleMap.insert(obj: $0)
            )
        }
    } while pollResult != UNIFFI_RUST_FUTURE_POLL_READY

    return try liftFunc(makeRustCall(
        { completeFunc(rustFuture, $0) },
        errorHandler: errorHandler
    ))
}

// Callback handlers for an async calls.  These are invoked by Rust when the future is ready.  They
// lift the return value or error and resume the suspended function.
fileprivate func uniffiFutureContinuationCallback(handle: UInt64, pollResult: Int8) {
    if let continuation = try? uniffiContinuationHandleMap.remove(handle: handle) {
        continuation.resume(returning: pollResult)
    } else {
        print("uniffiFutureContinuationCallback invalid handle")
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private var initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 26
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_zeroterm_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_hostkeypromptcallback_on_prompt() != 49474) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_sessionlistener_on_data() != 27884) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_sessionlistener_on_closed() != 42377) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_connect_host() != 4426) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_create() != 6614) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_delete_host() != 1418) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_disconnect_session() != 35863) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_forget_keychain() != 65474) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_list_hosts() != 46238) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_lock() != 8953) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_resize_session() != 30624) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_respond_host_key() != 23930) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_save_host() != 46912) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_send_input() != 32259) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_set_vault_path() != 22249) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_try_keychain_unlock() != 29568) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_unlock() != 21892) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_method_zeroterm_vault_status() != 24602) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_zeroterm_ffi_checksum_constructor_zeroterm_new() != 5407) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitHostKeyPromptCallback()
    uniffiCallbackInitSessionListener()
    return InitializationResult.ok
}()

private func uniffiEnsureInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all